version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key-change-this-in-production
    volumes:
      - .:/app
    restart: unless-stopped